#!/usr/bin/env python3
"""Create the concrete, restart-safe five-fold no-NMS experiment plan."""
from __future__ import annotations
import argparse, json
from pathlib import Path
import yaml
def read(p): return [x.strip() for x in Path(p).read_text().splitlines() if x.strip()]
def main():
 a=argparse.ArgumentParser(); a.add_argument('--config',required=True); a.add_argument('--work',required=True); a.add_argument('--epochs',type=int,default=12); z=a.parse_args(); c=yaml.safe_load(Path(z.config).read_text()); w=Path(z.work); f=w/'folds'; f.mkdir(parents=True,exist_ok=True); train=read(c['data']['train_ids']); stages=[{'name':'cache_4fps','command':'PYTHONPATH=.:football_e2e_spotter/src python football_e2e_spotter/scripts/build_pixel_audio_store.py --config football_e2e_spotter/configs/set_spotter_v1_cache.yaml --workers 8'}]; parts=[]
 for k in range(5):
  va=train[k::5]; tr=[v for i,v in enumerate(train) if i%5!=k]; tp=f/f'fold{k}_train.txt'; vp=f/f'fold{k}_valid.txt'; tp.write_text('\n'.join(tr)+'\n'); vp.write_text('\n'.join(va)+'\n'); ck=w/f'stage1_fold{k}'; cp=w/'oof'/f'fold{k}.jsonl'; parts.append(str(cp)); stages += [{'name':f'stage1_fold{k}','command':f'PYTHONPATH=.:football_e2e_spotter/src python football_e2e_spotter/train_set_spotter_ids.py --config {z.config} --ids {tp} --output {ck} --epochs {z.epochs}'},{'name':f'candidates_fold{k}','command':f'PYTHONPATH=.:football_e2e_spotter/src python football_e2e_spotter/run_set_candidates.py --config {z.config} --checkpoint {ck}/last.pt --ids {vp} --split train --output {cp} --threshold 0.01'}]
 oof=w/'oof/candidates.jsonl'; stages += [{'name':'merge_oof','command':f'python football_e2e_spotter/merge_jsonl.py --output {oof} '+' '.join(parts)},{'name':'verifier','command':f'PYTHONPATH=.:football_e2e_spotter/src python football_e2e_spotter/train_set_verifier.py --candidates {oof} --annotations {c["data"]["annotations"]} --output {w}/verifier --epochs 6'},{'name':'stage1_full','command':f'PYTHONPATH=.:football_e2e_spotter/src python football_e2e_spotter/train_set_spotter_ids.py --config {z.config} --ids {c["data"]["train_ids"]} --output {w}/stage1_full --epochs {z.epochs}'},{'name':'calibration_candidates','command':f'PYTHONPATH=.:football_e2e_spotter/src python football_e2e_spotter/run_set_candidates.py --config {z.config} --checkpoint {w}/stage1_full/last.pt --ids {c["data"]["calibration_ids"]} --split calibration --output {w}/calibration/candidates.jsonl --threshold 0.01'},{'name':'calibration_eval','command':f'PYTHONPATH=.:football_e2e_spotter/src python football_e2e_spotter/evaluate_set_pipeline.py --candidates {w}/calibration/candidates.jsonl --annotations {c["data"]["annotations"]} --verifier {w}/verifier/last.pt --output {w}/calibration'}]
 plan={'cwd':str(Path.cwd()),'no_temporal_nms':True,'stages':stages}; out=w/'watchdog_plan.json'; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(plan,indent=2)+'\n'); print(out)
if __name__=='__main__': main()
